# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
# Dockerfile for DocDocDoc MCP Server
FROM python:3.13-slim

# Set working directory
WORKDIR /app

# Copy project files
COPY . .

# Install dependencies
RUN pip install --no-cache-dir fastmcp requests

# Expose port if needed (stdio no)

# Default command (overridden by MCP startCommand)
CMD ["python3", "main.py"]
